[fire]
name = "fire-cone"
cast_name = "fire_cone"
element_type = ["fire"]
spell_range = 16.0
pattern = [0.0]
energy_cost = 28.5
spell_type = "explosion"
cast_type = {chargeup = { charge_type = ["damage"] }  }
cooldown_time = 3.72
charge_time = 2.12
cast_snd = "boom"

[ice]
name = "ice-spike"
cast_name = "ice_spike"
element_type = ["ice"]
spell_range = 20.0
pattern = [-8.6, -4.3, 0.0, 4.3, 8.6]
energy_cost = 12.5
spell_type = "projectile"
cast_type = "endofcharge"
cooldown_time = 0.82
charge_time = 0.5
cast_snd = "boom"

[electric]
name = "shock"
cast_name = "shock"
element_type = ["electric"]
spell_range = 20.0
pattern = [0.0]
energy_cost = 5.5
spell_type = "projectile"
cast_type = { whilecharging = { frequency = 0.1 } }
cooldown_time = 0.82
charge_time = 1.05
cast_snd = "boom"